name: foe
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h3237794_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38hb192615_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.6=h5499902_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py38he333c0f_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - c-blosc2=2.12.0=ha57e6be_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38h858044d_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - clarabel=0.7.1=py38hcc21af2_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h9afee92_1
  - cvxpy=1.5.3=py38h150bfb4_0
  - cvxpy-base=1.5.3=py38h0dc1a42_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - cytoolz=0.12.3=py38h336bac9_0
  - darkdetect=0.8.0=pyhd8ed1ab_0
  - dask-core=2023.5.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.5=py38h11842c7_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deepdiff=8.0.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.15=pyhff2d567_0
  - dipy=1.8.0=py38h9019b79_1
  - double-conversion=3.3.1=h286801f_0
  - ecos=2.0.14=py38h9f76b62_0
  - edflib-python=1.0.8=pyhd8ed1ab_0
  - eeglabio=0.0.2.post4=pyhd8ed1ab_0
  - eigen=3.4.0=h49c215f_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.7.3=haf25636_0
  - ffmpeg=6.1.2=gpl_hbafc610_106
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.53.1=py38h3237794_0
  - fooof=1.0.0=pyh5ca1d4c_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - frozenlist=1.4.1=py38h336bac9_0
  - fsspec=2024.10.0=pyhff2d567_0
  - future=1.0.0=pyhd8ed1ab_0
  - gl2ps=1.4.2=hc97c1ff_1
  - glew=2.1.0=h9f76cd9_2
  - glib=2.84.0=heee381b_0
  - glib-tools=2.84.0=h1dc7a0c_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - gst-plugins-base=1.24.11=h3c5c1d0_0
  - gstreamer=1.24.11=hfe24232_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5io=0.2.4=pyhecae5ae_0
  - h5py=3.11.0=nompi_py38h70800c8_102
  - harfbuzz=11.1.0=hab40de2_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.3=nompi_ha698983_109
  - hdf5storage=0.1.19=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_0
  - imagecodecs-lite=2019.12.3=py38h9f76b62_8
  - imageio=2.36.0=pyh12aca89_1
  - imageio-ffmpeg=0.5.1=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipycanvas=0.13.3=pyhd8ed1ab_0
  - ipyevents=2.0.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.12.2=pyhd1c38e8_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - ipyvtklink=0.2.3=pyhd8ed1ab_0
  - ipywidgets=7.8.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsoncpp=1.9.5=hc021e02_1
  - jsonpointer=3.0.0=py38h10201cd_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.7.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.11=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py38h9afee92_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libaec=1.1.4=h51d1e36_0
  - libass=0.17.3=h68e5b86_2
  - libblas=3.9.0=20_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=20_osxarm64_openblas
  - libclang-cpp17=17.0.6=default_hf90f093_8
  - libclang-cpp18.1=18.1.8=default_h73dfc95_16
  - libclang13=19.1.7=default_h6e8f826_5
  - libcurl=8.12.1=h73640d1_0
  - libcxx=21.1.7=hf598326_0
  - libdeflate=1.23=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.84.0=hdff4504_0
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=20_osxarm64_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - libllvm17=17.0.6=hc4b4ae8_3
  - libllvm18=18.1.8=hc4b4ae8_3
  - libllvm19=19.1.7=hc4b4ae8_1
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnetcdf=4.9.2=nompi_h610d594_116
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libopenvino=2024.4.0=hbfeda7a_2
  - libopenvino-arm-cpu-plugin=2024.4.0=hbfeda7a_2
  - libopenvino-auto-batch-plugin=2024.4.0=hf276634_2
  - libopenvino-auto-plugin=2024.4.0=hf276634_2
  - libopenvino-hetero-plugin=2024.4.0=h03892cd_2
  - libopenvino-ir-frontend=2024.4.0=h03892cd_2
  - libopenvino-onnx-frontend=2024.4.0=h7f5a098_2
  - libopenvino-paddle-frontend=2024.4.0=h7f5a098_2
  - libopenvino-pytorch-frontend=2024.4.0=h5833ebf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h9d544f2_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5833ebf_2
  - libopus=1.5.2=h48c0fde_0
  - libosqp=0.6.3=h5833ebf_1
  - libpng=1.6.53=hfab5511_0
  - libpq=17.7=h944245b_1
  - libprotobuf=5.28.2=h8f0b736_0
  - libqdldl=0.1.7=hb7217d7_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libtheora=1.1.1=h99b78c6_1006
  - libtiff=4.7.0=h551f018_3
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libxslt=1.1.43=h429d6fd_0
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - littleutils=0.2.4=pyhd8ed1ab_0
  - llvm-openmp=21.1.7=h4a912ad_0
  - llvmlite=0.41.1=py38hbed3d3f_0
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.7.2=py38h10201cd_1
  - lxml=5.3.0=py38hdedcbec_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=2.1.5=py38h336bac9_0
  - matplotlib=3.7.3=py38h150bfb4_0
  - matplotlib-base=3.7.3=py38hef9d0d7_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mffpy=0.10.0=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mne=1.0.3=hd8ed1ab_1
  - mne-base=1.0.3=pyh57928b3_3
  - mne-qt-browser=0.6.3=pyha770c72_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py38h4b8c310_0
  - multidict=6.0.5=py38hb991d35_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=hd7719f6_4
  - mysql-libs=9.0.1=ha8be5b7_4
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhff2d567_2
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nibabel=5.2.1=pyha770c72_0
  - nilearn=0.10.4=pyhd8ed1ab_0
  - nlohmann_json=3.12.0=h248ca61_1
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - nspr=4.38=heaf21c2_0
  - nss=3.118=h1c710a3_0
  - numba=0.58.1=py38hbe32c8a_0
  - numexpr=2.8.4=py38hefb543e_1
  - numpy=1.24.4=py38ha84db1f_0
  - openh264=2.4.1=hebf3989_0
  - openjpeg=2.5.3=h889cd5d_1
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - orderly-set=5.2.2=pyhd8ed1ab_0
  - osqp=0.6.7.post0=py38h0dc1a42_0
  - outdated=0.2.2=pyhd8ed1ab_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.5.3=py38h61dac83_1
  - pandas-flavor=0.6.0=pyhd8ed1ab_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=ha881caa_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h2c6aaed_0
  - pingouin=0.5.5=pyhd8ed1ab_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - pooch=1.8.2=pyhd8ed1ab_0
  - proj=9.4.1=hfb94cee_1
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=6.0.0=py38h3237794_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.14=h13dd4ca_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pymatreader=0.0.32=pyhd8ed1ab_0
  - pyopengl=3.1.6=pyhd8ed1ab_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.9=py38h951d1d4_5
  - pyqt5-sip=12.12.2=py38he333c0f_5
  - pyqtgraph=0.13.3=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.8.0=py38hcf313c7_4
  - python=3.8.19=h2469fbe_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-picard=0.8=pyha308f57_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyvista=0.44.2=pyhd8ed1ab_0
  - pyvistaqt=0.11.1=pyhd8ed1ab_0
  - pywavelets=1.4.1=py38h5912bca_1
  - pyyaml=6.0.2=py38h3237794_0
  - pyzmq=26.2.0=py38h7e0d939_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_0
  - qdldl-python=0.1.7.post4=py38h0dc1a42_0
  - qt-main=5.15.15=h67564f6_2
  - qt6-main=6.8.2=h4464394_0
  - qtpy=2.4.2=pyhdecd6ff_0
  - readline=8.2=h1d1bf99_2
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py38h186058e_0
  - scikit-image=0.19.3=py38h61dac83_2
  - scikit-learn=1.3.2=py38he1bc1c9_2
  - scipy=1.10.1=py38h038e806_3
  - scooby=0.10.0=pyhd8ed1ab_0
  - scs=3.2.7=default_py38h2895e65_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - setuptools-scm=8.1.0=pyhd8ed1ab_0
  - sip=6.8.3=py38hb9fa5a8_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.6=pyhd8ed1ab_0
  - sqlite=3.51.1=he8f07e4_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py38hd97cf01_0
  - svt-av1=2.3.0=hf24288c_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2022.3.0=h66ce52b_1
  - tbb-devel=2022.3.0=h41f9aa9_1
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2020.6.3=py_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_3
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py38h3237794_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trx-python=0.3=py38h10201cd_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py38hb192615_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - utfcpp=4.0.8=hce30654_0
  - vtk=9.3.1=qt_py38h07c347a_204
  - vtk-base=9.3.1=qt_py38h9391cbe_204
  - vtk-io-ffmpeg=9.3.1=qt_py38h64321a6_204
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.10=pyhd8ed1ab_0
  - wrapt=1.16.0=py38h336bac9_0
  - wslink=2.2.1=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xarray=2023.1.0=pyhd8ed1ab_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xmltodict=0.14.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.9.4=py38h336bac9_0
  - zeromq=4.3.5=hcc0f68c_4
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.0.7=h1a8c8d9_0
  - zstandard=0.23.0=py38h43bb1b3_0
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - coverage==6.5.0
      - irrcac==0.4.0
      - pyhht==0.1.0
prefix: /Users/alexandratautan/miniforge3/envs/foe
